In [1]:
import numpy as np

In [2]:
cupcakes = np.array([2, 0.75, 2, 1, 0.5])

In [5]:
recipes = np.genfromtxt("recipes.csv", delimiter = ",")
print(recipes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]


In [7]:
eggs = recipes[:, 2]
#eggs

array([2., 1., 1., 2.])

In [8]:
one_egg_recipes = recipes[eggs == 1]
print(one_egg_recipes)

[[1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]]


In [9]:
cookies = recipes[2, :]
#cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

In [10]:
double_batch = cupcakes * 2
#double_batch

array([4. , 1.5, 4. , 2. , 1. ])

In [11]:
grocery_list = cookies + double_batch
#grocery_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])